# Ref: https://ethereum.github.io/yellowpaper/paper.pdf
# Generated from `python erever/convert_opcode_table.py`

OPCODES = {
    # value: (mnemonic, stack input count, stack output count, description)
    0x00: ("STOP", 0, 0, "Halts execution."),
    0x01: ("ADD", 2, 1, "Addition operation."),
    0x02: ("MUL", 2, 1, "Multiplication operation."),
    0x03: ("SUB", 2, 1, "Subtraction operation."),
    0x04: ("DIV", 2, 1, "Integer division operation."),
    0x05: ("SDIV", 2, 1, "Signed integer division operation (truncated)."),
    0x06: ("MOD", 2, 1, "Modulo remainder operation."),
    0x07: ("SMOD", 2, 1, "Signed modulo remainder operation."),
    0x08: ("ADDMOD", 3, 1, "Modulo addition operation."),
    0x09: ("MULMOD", 3, 1, "Modulo multiplication operation."),
    0x0a: ("EXP", 2, 1, "Exponential operation."),
    0x0b: ("SIGNEXTEND", 2, 1, "Extend length of two's complement signed integer."),
    0x10: ("LT", 2, 1, "Less-than comparison."),
    0x11: ("GT", 2, 1, "Greater-than comparison."),
    0x12: ("SLT", 2, 1, "Signed less-than comparison."),
    0x13: ("SGT", 2, 1, "Signed greater-than comparison."),
    0x14: ("EQ", 2, 1, "Equality comparison."),
    0x15: ("ISZERO", 1, 1, "Simple not operator."),
    0x16: ("AND", 2, 1, "Bitwise AND operation."),
    0x17: ("OR", 2, 1, "Bitwise OR operation."),
    0x18: ("XOR", 2, 1, "Bitwise XOR operation."),
    0x19: ("NOT", 1, 1, "Bitwise NOT operation."),
    0x1a: ("BYTE", 2, 1, "Retrieve single byte from word."),
    0x1b: ("SHL", 2, 1, "Left shift operation."),
    0x1c: ("SHR", 2, 1, "Logical right shift operation."),
    0x1d: ("SAR", 2, 1, "Arithmetic (signed) right shift operation."),
    0x20: ("KECCAK256", 2, 1, "Compute Keccak-256 hash."),
    0x30: ("ADDRESS", 0, 1, "Get address of currently executing account."),
    0x31: ("BALANCE", 1, 1, "Get balance of the given account."),
    0x32: ("ORIGIN", 0, 1, "Get execution origination address."),
    0x33: ("CALLER", 0, 1, "Get caller address."),
    0x34: ("CALLVALUE", 0, 1, "Get deposited value by the instruction/transaction responsible for this execution."),
    0x35: ("CALLDATALOAD", 1, 1, "Get input data of current environment."),
    0x36: ("CALLDATASIZE", 0, 1, "Get size of input data in current environment."),
    0x37: ("CALLDATACOPY", 3, 0, "Copy input data in current environment to memory."),
    0x38: ("CODESIZE", 0, 1, "Get size of code running in current environment."),
    0x39: ("CODECOPY", 3, 0, "Copy code running in current environment to memory."),
    0x3a: ("GASPRICE", 0, 1, "Get price of gas in current environment."),
    0x3b: ("EXTCODESIZE", 1, 1, "Get size of an account's code."),
    0x3c: ("EXTCODECOPY", 4, 0, "Copy an account's code to memory."),
    0x3d: ("RETURNDATASIZE", 0, 1, "Get size of output data from the previous call from the current environment."),
    0x3e: ("RETURNDATACOPY", 3, 0, "Copy output data from the previous call to memory."),
    0x3f: ("EXTCODEHASH", 1, 1, "Get hash of an account's code."),
    0x40: ("BLOCKHASH", 1, 1, "Get the hash of one of the 256 most recent complete blocks."),
    0x41: ("COINBASE", 0, 1, "Get the current block's beneficiary address."),
    0x42: ("TIMESTAMP", 0, 1, "Get the current block's timestamp."),
    0x43: ("NUMBER", 0, 1, "Get the current block's number."),
    0x44: ("DIFFICULTY", 0, 1, "Get the current block's difficulty."),
    0x45: ("GASLIMIT", 0, 1, "Get the current block's gas limit."),
    0x46: ("CHAINID", 0, 1, "Get the chain ID."),
    0x47: ("SELFBALANCE", 0, 1, "Get balance of currently executing account."),
    0x50: ("POP", 1, 0, "Remove item from stack."),
    0x51: ("MLOAD", 1, 1, "Load word from memory."),
    0x52: ("MSTORE", 2, 0, "Save word to memory."),
    0x53: ("MSTORE8", 2, 0, "Save byte to memory."),
    0x54: ("SLOAD", 1, 1, "Load word from storage."),
    0x55: ("SSTORE", 2, 0, "Save word to storage."),
    0x56: ("JUMP", 1, 0, "Alter the program counter."),
    0x57: ("JUMPI", 2, 0, "Conditionally alter the program counter."),
    0x58: ("PC", 0, 1, "Get the value of the program counter prior to the increment corresponding to this instruction."),
    0x59: ("MSIZE", 0, 1, "Get the size of active memory in bytes."),
    0x5a: ("GAS", 0, 1, "Get the amount of available gas, including the corresponding reduction for the cost of this instruction."),
    0x5b: ("JUMPDEST", 0, 0, "Mark a valid destination for jumps."),
    0x60: ("PUSH1", 0, 1, "Place 1 byte item on stack."),
    0x61: ("PUSH2", 0, 1, "Place 2 byte item on stack."),
    0x62: ("PUSH3", 0, 1, "Place 3 byte item on stack."),
    0x63: ("PUSH4", 0, 1, "Place 4 byte item on stack."),
    0x64: ("PUSH5", 0, 1, "Place 5 byte item on stack."),
    0x65: ("PUSH6", 0, 1, "Place 6 byte item on stack."),
    0x66: ("PUSH7", 0, 1, "Place 7 byte item on stack."),
    0x67: ("PUSH8", 0, 1, "Place 8 byte item on stack."),
    0x68: ("PUSH9", 0, 1, "Place 9 byte item on stack."),
    0x69: ("PUSH10", 0, 1, "Place 10 byte item on stack."),
    0x6a: ("PUSH11", 0, 1, "Place 11 byte item on stack."),
    0x6b: ("PUSH12", 0, 1, "Place 12 byte item on stack."),
    0x6c: ("PUSH13", 0, 1, "Place 13 byte item on stack."),
    0x6d: ("PUSH14", 0, 1, "Place 14 byte item on stack."),
    0x6e: ("PUSH15", 0, 1, "Place 15 byte item on stack."),
    0x6f: ("PUSH16", 0, 1, "Place 16 byte item on stack."),
    0x70: ("PUSH17", 0, 1, "Place 17 byte item on stack."),
    0x71: ("PUSH18", 0, 1, "Place 18 byte item on stack."),
    0x72: ("PUSH19", 0, 1, "Place 19 byte item on stack."),
    0x73: ("PUSH20", 0, 1, "Place 20 byte item on stack."),
    0x74: ("PUSH21", 0, 1, "Place 21 byte item on stack."),
    0x75: ("PUSH22", 0, 1, "Place 22 byte item on stack."),
    0x76: ("PUSH23", 0, 1, "Place 23 byte item on stack."),
    0x77: ("PUSH24", 0, 1, "Place 24 byte item on stack."),
    0x78: ("PUSH25", 0, 1, "Place 25 byte item on stack."),
    0x79: ("PUSH26", 0, 1, "Place 26 byte item on stack."),
    0x7a: ("PUSH27", 0, 1, "Place 27 byte item on stack."),
    0x7b: ("PUSH28", 0, 1, "Place 28 byte item on stack."),
    0x7c: ("PUSH29", 0, 1, "Place 29 byte item on stack."),
    0x7d: ("PUSH30", 0, 1, "Place 30 byte item on stack."),
    0x7e: ("PUSH31", 0, 1, "Place 31 byte item on stack."),
    0x7f: ("PUSH32", 0, 1, "Place 32-byte (full word) item on stack."),
    0x80: ("DUP1", 1, 2, "Duplicate 1st stack item."),
    0x81: ("DUP2", 2, 3, "Duplicate 2nd stack item."),
    0x82: ("DUP3", 3, 4, "Duplicate 3rd stack item."),
    0x83: ("DUP4", 4, 5, "Duplicate 4th stack item."),
    0x84: ("DUP5", 5, 6, "Duplicate 5th stack item."),
    0x85: ("DUP6", 6, 7, "Duplicate 6th stack item."),
    0x86: ("DUP7", 7, 8, "Duplicate 7th stack item."),
    0x87: ("DUP8", 8, 9, "Duplicate 8th stack item."),
    0x88: ("DUP9", 9, 10, "Duplicate 9th stack item."),
    0x89: ("DUP10", 10, 11, "Duplicate 10th stack item."),
    0x8a: ("DUP11", 11, 12, "Duplicate 11th stack item."),
    0x8b: ("DUP12", 12, 13, "Duplicate 12th stack item."),
    0x8c: ("DUP13", 13, 14, "Duplicate 13th stack item."),
    0x8d: ("DUP14", 14, 15, "Duplicate 14th stack item."),
    0x8e: ("DUP15", 15, 16, "Duplicate 15th stack item."),
    0x8f: ("DUP16", 16, 17, "Duplicate 16th stack item."),
    0x90: ("SWAP1", 2, 2, "Exchange 1st and 2nd stack items."),
    0x91: ("SWAP2", 3, 3, "Exchange 1st and 3rd stack items."),
    0x92: ("SWAP3", 4, 4, "Exchange 1st and 4th stack items."),
    0x93: ("SWAP4", 5, 5, "Exchange 1st and 5th stack items."),
    0x94: ("SWAP5", 6, 6, "Exchange 1st and 6th stack items."),
    0x95: ("SWAP6", 7, 7, "Exchange 1st and 7th stack items."),
    0x96: ("SWAP7", 8, 8, "Exchange 1st and 8th stack items."),
    0x97: ("SWAP8", 9, 9, "Exchange 1st and 9th stack items."),
    0x98: ("SWAP9", 10, 10, "Exchange 1st and 10th stack items."),
    0x99: ("SWAP10", 11, 11, "Exchange 1st and 11th stack items."),
    0x9a: ("SWAP11", 12, 12, "Exchange 1st and 12th stack items."),
    0x9b: ("SWAP12", 13, 13, "Exchange 1st and 13th stack items."),
    0x9c: ("SWAP13", 14, 14, "Exchange 1st and 14th stack items."),
    0x9d: ("SWAP14", 15, 15, "Exchange 1st and 15th stack items."),
    0x9e: ("SWAP15", 16, 16, "Exchange 1st and 16th stack items."),
    0x9f: ("SWAP16", 17, 17, "Exchange 1st and 17th stack items."),
    0xa0: ("LOG0", 2, 0, "Append log record with no topics."),
    0xa1: ("LOG1", 3, 0, "Append log record with one topic."),
    0xa2: ("LOG2", 4, 0, "Append log record with two topics."),
    0xa3: ("LOG3", 5, 0, "Append log record with three topics."),
    0xa4: ("LOG4", 6, 0, "Append log record with four topics."),
    0xf0: ("CREATE", 3, 1, "Create a new account with associated code."),
    0xf1: ("CALL", 7, 1, "Message-call into an account."),
    0xf2: ("CALLCODE", 7, 1, "Message-call into this account with an alternative account's code."),
    0xf3: ("RETURN", 2, 0, "Halt execution returning output data."),
    0xf4: ("DELEGATECALL", 6, 1, "Message-call into this account with an alternative account's code, but persisting the current values for sender and value."),
    0xfa: ("STATICCALL", 6, 1, "Static message-call into an account."),
    0xfd: ("REVERT", 2, 0, "Halt execution reverting state changes but returning data and remaining gas."),
    0xfe: ("INVALID", 0, 0, "Designated invalid instruction."),
    0xff: ("SELFDESTRUCT", 1, 0, "Halt execution and register account for later deletion."),
}